# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

target 'Calculator' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calculator
  pod 'SnapKit', '~> 4.0.0'
  pod 'AnushkTestSDK', :path => '../../AnushkTestSDK', :configurations => ['Debug']
end
